### PR TITLE
fix(framework): enforce eslint to fail on warnings

### LINKED ISSUE #492: make sure eslint fails on warnings everywhere
## Context

Right now warnings are ignored everywhere but on the documentation website.

## Goal

Adjust the eslint call for every project part, so that warnings make it fail as well.

```bash
--report-unused-disable-directives --max-warnings 0
```

### PR DESCRIPTION
**Pull request by itsmacr8**
# The Pull Request is ready

- [x] fixes #492 
- [ ] all actions are passing
- [x] only fixes a single issue

## Overview

Add "--report-unused-disable-directives --max-warnings 0" to the package.json script to ensure eslint fails on any warnings, aligning with the project's code quality standards.

## Framework

- [x] the change breaks no interface
- [x] default behaviour did not change
- [ ] any new text output is added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] documentation has been adjusted (if required)
- [ ] shared code has been extracted in a different file

### CODE REVIEW

**Comment by Idrinth** [comment]
hi @itsmacr8 ,
please update your branch and quickly fix the found issues :) otherwise this is perfect.

**Comment by Idrinth** [comment]
> Hey, @Idrinth, are you talking about the failed test (ESLINT / framework (pull_request))? If yes, can you give me context on why it might happen?

you can see the output if you run `npm run lint` locally or when clicking on Details in the check list.

**Comment by itsmacr8** [comment]
Screenshot (210)
I have to remove those redundant lines (    // eslint-disable-next-line @typescript-eslint/no-empty-function) from every file?

**Comment by Idrinth** [comment]
> Screenshot (210) I have to remove those redundant lines ( // eslint-disable-next-line @typescript-eslint/no-empty-function) from every file?

yes please

**Comment by itsmacr8** [comment]
If I remove them, then it creates no unused var. It makes sense. Now, what? just push the codes?

**Comment by Idrinth** [comment]
> If I remove them, then it creates no unused var. It makes sense. Now, what? just push the codes?

what did you remove?

**Comment by itsmacr8** [comment]
Sorry for the confusion. By mistake I also removed the "@typescript-eslint/no-unused-vars".

**Comment by Idrinth** [comment]
> Sorry for the confusion. By mistake I also removed the "@typescript-eslint/no-unused-vars".

all good :) see it as a learning experience

**Comment by itsmacr8** [comment]
Screenshot (211)

The problem is not on my local machine. But why it showing here? @Idrinth

**Comment by Idrinth** [comment]
> The problem is not on my local machine. But why it showing here? @Idrinth

Actually not sure, it is an old problem, that shouldn't have made stuff fail - will double check

**Pull request merged**
